export const ADD_USER="ADD_USER";
export const UPDATE_USER="UPDATE_USER";
export const LOADING_USER="LOADING_USER";
export const DELETE_USER="DELETE_USER";
export const ERROR_USER="ERROR_USER";
export const ADD_UNREAD_COUNT="ADD_UNREAD_COUNT";
export const DELETE_UNREAD_COUNT="DELETE_UNREAD_COUNT";