require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PocketDoc' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'PocketDocTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'PocketDoc-tvOS' do
  # Pods for PocketDoc-tvOS

  target 'PocketDoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
